'use client';

import { AlertCircle } from 'lucide-react';

interface CreateGuideProps {
  service: 'supabase';
  show: boolean;
  onCopy: (text: string) => void;
}

// Supabase keep_alive 表创建脚本
// 如果已有旧表，请先删除后再执行此脚本
const supabaseMigrateSQL = `-- 创建 keep_alive 表
CREATE TABLE IF NOT EXISTS keep_alive (
  service TEXT PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  manual_count INTEGER NOT NULL DEFAULT 0,
  auto_count INTEGER NOT NULL DEFAULT 0,
  failure_count INTEGER NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- 初始化服务记录
INSERT INTO keep_alive (service, timestamp, manual_count, auto_count, enabled)
VALUES 
  ('supabase', NOW(), 0, 0, TRUE),
  ('leancloud', NOW(), 0, 0, TRUE),
  ('glados', NOW(), 0, 0, TRUE)
ON CONFLICT (service) DO NOTHING;

-- 启用行级安全策略 (RLS)
ALTER TABLE keep_alive ENABLE ROW LEVEL SECURITY;

-- 创建 keep_alive_logs 表 (v0.8.0 新增)
CREATE TABLE IF NOT EXISTS keep_alive_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service TEXT NOT NULL,
  status BOOLEAN NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 为日志表启用 RLS
ALTER TABLE keep_alive_logs ENABLE ROW LEVEL SECURITY;

-- 创建索引以优化热力图查询
CREATE INDEX IF NOT EXISTS idx_logs_timestamp_service ON keep_alive_logs (timestamp, service);`;

// LeanCloud class creation REST API command

/**
 * 表/类创建引导组件
 *
 * 为 Supabase 和 LeanCloud 提供不同的创建指导
 */
export function CreateGuide({ service, show, onCopy }: CreateGuideProps) {
  if (!show) return null;

  if (service === 'supabase') {
    return (
      <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-md">
        <div className="flex items-start gap-2 mb-2">
          <AlertCircle className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
          <div className="flex-1">
            <p className="text-sm font-medium text-amber-900 mb-1">Database Setup Required</p>
            <p className="text-xs text-amber-700 leading-relaxed">
              The{' '}
              <code className="px-1 py-0.5 bg-amber-100 rounded text-amber-900">keep_alive</code>{' '}
              table needs to be set up or migrated. Copy the SQL below and execute it in your
              Supabase SQL Editor.
            </p>
          </div>
        </div>
        <button
          onClick={() => onCopy(supabaseMigrateSQL)}
          className="mt-2 flex items-center gap-2 px-3 py-1.5 bg-amber-100 hover:bg-amber-200 text-amber-900 text-xs font-medium rounded border border-amber-300 transition-colors"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
            />
          </svg>
          Copy Migration SQL
        </button>
      </div>
    );
  }
  return null;
}
