-- 创建 keep_alive 表
-- 用于存储所有服务的保活状态和开关配置
-- 注意：记录会在首次 Run Task 时自动创建，此初始化为可选

CREATE TABLE IF NOT EXISTS keep_alive (
  service TEXT PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  manual_count INTEGER NOT NULL DEFAULT 0,
  auto_count INTEGER NOT NULL DEFAULT 0,
  failure_count INTEGER NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

-- 可选：预初始化服务记录（如需在首次运行前使用开关功能）
INSERT INTO keep_alive (service, timestamp, manual_count, auto_count, enabled)
VALUES 
  ('supabase', NOW(), 0, 0, TRUE),
  ('glados', NOW(), 0, 0, TRUE)
ON CONFLICT (service) DO NOTHING;

-- 启用行级安全策略 (RLS)
ALTER TABLE keep_alive ENABLE ROW LEVEL SECURITY;

-- 创建 keep_alive_logs 表 (v0.8.0 新增)
-- 用于记录每次执行的详细日志，支持热力图统计
CREATE TABLE IF NOT EXISTS keep_alive_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success', 'failure')),
  message TEXT,
  duration INTEGER, -- 执行耗时 (ms)
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 为日志表启用 RLS
ALTER TABLE keep_alive_logs ENABLE ROW LEVEL SECURITY;

-- 创建索引以优化热力图查询 (按时间范围和状态过滤)
CREATE INDEX IF NOT EXISTS idx_logs_timestamp_service ON keep_alive_logs (timestamp, service);
