-- ==========================================
-- Workflow Operations - 完整数据库初始化脚本
-- 版本: v1.1.0 (最新同步)
-- 说明: 包含基础表结构、动态配置扩展及初始数据
-- ==========================================

-- 1. 创建 keep_alive 表 (核心配置表)
CREATE TABLE IF NOT EXISTS keep_alive (
  service TEXT PRIMARY KEY,
  name TEXT,                                    -- 显示名称
  description TEXT,                             -- 任务描述
  category TEXT,                                -- 任务分类
  type TEXT DEFAULT 'http',                     -- 任务类型 (http/supabase_internal)
  config JSONB DEFAULT '{}'::jsonB,             -- HTTP 请求配置 (URL, Headers, Body)
  rules JSONB DEFAULT '{}'::jsonB,              -- 校验规则 (Success/Increment)
  notification_level TEXT DEFAULT 'failure-only',-- 通知级别 (always/failure-only/none)
  enabled BOOLEAN NOT NULL DEFAULT TRUE,         -- 是否启用自动任务
  manual_count INTEGER NOT NULL DEFAULT 0,       -- 手动执行计数
  auto_count INTEGER NOT NULL DEFAULT 0,         -- 自动执行计数
  failure_count INTEGER NOT NULL DEFAULT 0,      -- 失败计数
  last_run_at TIMESTAMPTZ,                       -- 最后一次运行时间
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()   -- 创建时间
);

-- 2. 创建 keep_alive_logs 表 (执行日志表，支持热力图)
CREATE TABLE IF NOT EXISTS keep_alive_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success', 'failure')),
  message TEXT,
  duration INTEGER,                              -- 执行耗时 (ms)
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. 启用行级安全策略 (RLS)
ALTER TABLE keep_alive ENABLE ROW LEVEL SECURITY;
ALTER TABLE keep_alive_logs ENABLE ROW LEVEL SECURITY;

-- 4. 创建性能优化索引
CREATE INDEX IF NOT EXISTS idx_logs_timestamp_service ON keep_alive_logs (timestamp, service);

-- 5. 初始化内置服务数据
INSERT INTO keep_alive (service, name, description, category, type, config, rules)
VALUES 
  (
    'supabase', 
    'Supabase 保活', 
    '触发每日活跃信号，防止项目被暂停。', 
    'Database Maintenance', 
    'supabase_internal', 
    '{}'::jsonb, 
    '{}'::jsonb
  ),
  (
    'glados', 
    'GLaDOS 签到', 
    '每日签到以维持网络访问权限。', 
    'Access Protocol', 
    'http', 
    '{
      "urls": ["https://glados.rocks/api/user/checkin", "https://glados.cloud/api/user/checkin"],
      "method": "POST",
      "headers": {"Content-Type": "application/json"},
      "body": "{\"token\": \"glados.cloud\"}"
    }'::jsonb, 
    '{
      "success": {
        "status": 200,
        "json": [{"path": "code", "operator": "in", "value": [0, 1]}]
      },
      "increment": {
        "json": [{"path": "code", "operator": "eq", "value": 0}]
      }
    }'::jsonb
  )
ON CONFLICT (service) DO NOTHING;
