-- Workflow Operations Center - 数据库初始化脚本 (V2.1)
-- 适用范围: 核心表结构、索引及 RLS 安全策略加固
-- 迁移自: setup.sql

-- 1. 表结构 (Tables)
CREATE TABLE IF NOT EXISTS public.service_configs (
  service           TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  description       TEXT,
  category          TEXT DEFAULT 'uncategorized',
  type              TEXT DEFAULT 'http' CHECK (type IN ('http', 'supabase_internal')),
  config            JSONB DEFAULT '{}'::jsonb,
  rules             JSONB DEFAULT '{}'::jsonb,
  notification_level TEXT DEFAULT 'failure-only' CHECK (notification_level IN ('always', 'failure-only', 'none')),
  enabled           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.service_stats (
  service           TEXT PRIMARY KEY REFERENCES public.service_configs(service) ON DELETE CASCADE,
  manual_count      INTEGER NOT NULL DEFAULT 0,
  auto_count        INTEGER NOT NULL DEFAULT 0,
  failure_count     INTEGER NOT NULL DEFAULT 0,
  last_run_at       TIMESTAMPTZ,
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.keep_alive (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service           TEXT UNIQUE NOT NULL,
  last_active_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.keep_alive_logs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service           TEXT NOT NULL,
  status            TEXT NOT NULL CHECK (status IN ('success', 'failure')),
  message           TEXT,
  duration          INTEGER,
  timestamp         TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 索引 (Indexes)
CREATE INDEX IF NOT EXISTS idx_logs_main ON public.keep_alive_logs (timestamp DESC, service);
CREATE INDEX IF NOT EXISTS idx_logs_svc ON public.keep_alive_logs (service);
CREATE INDEX IF NOT EXISTS idx_ka_svc ON public.keep_alive (service);

-- 3. 安全策略 (RLS)
ALTER TABLE public.service_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keep_alive_logs ENABLE ROW LEVEL SECURITY;

-- 3.1 Authenticated 权限 (管理)
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "auth_all_configs" ON public.service_configs;
    CREATE POLICY "auth_all_configs" ON public.service_configs FOR ALL TO authenticated USING (true);
    
    DROP POLICY IF EXISTS "auth_all_stats" ON public.service_stats;
    CREATE POLICY "auth_all_stats" ON public.service_stats FOR ALL TO authenticated USING (true);
    
    DROP POLICY IF EXISTS "auth_read_logs" ON public.keep_alive_logs;
    CREATE POLICY "auth_read_logs" ON public.keep_alive_logs FOR ALL TO authenticated USING (true);
END $$;

-- 3.2 Public 权限 (心跳限制)
-- 仅允许 public 角色进行必要的读取和更新，禁止删除。
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "pub_heartbeat" ON public.keep_alive;
    
    DROP POLICY IF EXISTS "pub_heartbeat_read" ON public.keep_alive;
    CREATE POLICY "pub_heartbeat_read" ON public.keep_alive FOR SELECT TO public USING (true);

    DROP POLICY IF EXISTS "pub_heartbeat_insert" ON public.keep_alive;
    CREATE POLICY "pub_heartbeat_insert" ON public.keep_alive FOR INSERT TO public WITH CHECK (true);

    DROP POLICY IF EXISTS "pub_heartbeat_update" ON public.keep_alive;
    CREATE POLICY "pub_heartbeat_update" ON public.keep_alive FOR UPDATE TO public USING (true) WITH CHECK (true);
END $$;
